celeba_config = {
    'model': 'BigGAN',
    'G_param': 'SN',
    'D_param': 'SN',
    'G_ch': 96,
    'D_ch': 96, 'G_depth': 1,
    'D_depth': 1,
    'D_wide': True,
    'G_shared': True,
    'shared_dim': 128,
    'dim_z': 120,
    'z_var': 1.0,
    'hier': True,
    'cross_replica': False,
    'G_nl': 'inplace_relu',
    'D_nl': 'inplace_relu',
    'G_attn': '64',
    'D_attn': '64',
    'seed': 0,
    'G_init': 'ortho',
    'D_init': 'ortho',
    'skip_init': True,
    'batch_size': 1,
    'G_batch_size': 1,
    'num_G_accumulations': 8,
    'num_D_accumulations': 8,
    'num_epochs': 100,
    'G_fp16': False,
    'D_fp16': False,
    'ema': True,
    'num_G_SVs': 1,
    'num_D_SVs': 1,
    'num_G_SV_itrs': 1,
    'num_D_SV_itrs': 1,
    'G_ortho': 0.0,
    'D_ortho': 0.0,
    'device': 'cuda',
    'n_classes': 1000,
    'experiment_name': '138k',
    'lr': 0.01,
    'optimization_steps': 600,
    # SMYRF configuration
    'smyrf': False,
    'clustering_algo': 'lsh',
    'n_hashes': 8,
    'q_cluster_size': 1024,
    'k_cluster_size': 256,
    'q_attn_size': 1024,
    'k_attn_size': 256,
    ## K-means
    'max_iters': 30,
    'progress': False,
    ## LSH
    'r': 4,
    # Metrics configuration
    'dataset': 'celeba',
    'num_inception_images': 10000,
    # Checkpointing
    'resume': False,
    'load_weights': '',
    'weights_root': 'celeba_weights',
    'base_root': 'celeba_base',
    'experiment_name': 'celeba1024',

}
